### ISSUE TITLE
Kind request to hide package from Atmosphere

### ISSUE THREAD

**Issue by dandv** [andruschka/meteor-bootstrap-simplex#1]
Hey Andrej,

Current Meteor 3rd party packaging best practices recommend including the upstream as a submodule in the wrapper repo, then creating `package.js` files that refer to it. Also, the sources should be un-minified.

I went ahead and published [all Bootswatch themes](https://atmospherejs.com/bootswatch) that way so you don't have to worry about this stuff. Here's [the source repo](https://github.com/MeteorPackaging/bootswatch).

If you can do the community a favor, can you please hide the old package? It will still be installable by apps and dependent packages; it will just be hidden from Atmosphere searches:

```
meteor admin set-unmigrated andruschka:bootstrap-simplex
```

Thanks,
Dan
Atmosphere curator

**Comment by andruschka** [comment]
done
